Citizen.CreateThread(function()
	OnEnterMp()
	LoadMpDlcMaps()
	EnableMpDlcMaps(true)
	SetInstancePriorityMode(true)
	SetAudioFlag("ActivateSwitchWheelAudio", false)
	RequestIpl("dt1_03_gr_closed")
	RequestIpl("bkr_v_carmod3_milo_")
	RequestIpl('TrevorsTrailerTrash')
	RequestIpl('post_hiest_unload')
	RequestIpl('refit_unload')
	RequestIpl('FINBANK')
	RequestIpl('Coroner_Int_on')
	RequestIpl('coronertrash')
	RequestIpl('CS1_02_cf_onmission1')
	RequestIpl('CS1_02_cf_onmission2')
	RequestIpl('CS1_02_cf_onmission3')
	RequestIpl('CS1_02_cf_onmission4')
	RequestIpl('farm')
	RequestIpl('farmint')
	RequestIpl('farm_lod')
	RequestIpl('farm_props')
	RequestIpl('des_farmhouse')
	RequestIpl('FIBlobby')
	RequestIpl('FruitBB')
	RequestIpl("dt1_21_prop_lift")
	RequestIpl("dt1_21_prop_lift_on")
	RequestIpl('sc1_01_newbill')
	RequestIpl('hw1_02_newbill')
	RequestIpl('hw1_emissive_newbill')
	RequestIpl('sc1_14_newbill')
	RequestIpl('dt1_17_newbill')
	RequestIpl('id2_14_during_door')
	RequestIpl('id2_14_during1')
	RequestIpl('facelobby')
	RequestIpl('v_tunnel_hole')
	RequestIpl('Carwash_with_spinners')
	RequestIpl('sp1_10_real_interior')
	RequestIpl('sp1_10_real_interior_lod')
	RequestIpl('ch1_02_open')
	RequestIpl('bkr_bi_id1_23_door')
	RequestIpl('lr_cs6_08_grave_closed')
	RequestIpl('methtrailer_grp1')
	RequestIpl('bkr_bi_hw1_13_int')
	RequestIpl('CanyonRvrShallow')
	RequestIpl('CS3_07_MPGates')
	RequestIpl('bh1_47_joshhse_unburnt')
	RequestIpl('bh1_47_joshhse_unburnt_lod')
	RequestIpl('cs3_05_water_grp1')
	RequestIpl('cs3_05_water_grp1_lod')
	RequestIpl('cs3_05_water_grp2')
	RequestIpl('cs3_05_water_grp2_lod')
	RequestIpl('canyonriver01')
	RequestIpl('canyonriver01_lod')
	RequestIpl('ch3_rd2_bishopschickengraffiti')
	RequestIpl('cs5_04_mazebillboardgraffiti')
	RequestIpl('cs5_roads_ronoilgraffiti')
	-- RequestIpl('hei_carrier')
	-- RequestIpl('hei_carrier_distantlights')
	-- RequestIpl('hei_Carrier_int1')
	-- RequestIpl('hei_Carrier_int2')
	-- RequestIpl('hei_Carrier_int3')
	-- RequestIpl('hei_Carrier_int4')
	-- RequestIpl('hei_Carrier_int5')
	-- RequestIpl('hei_Carrier_int6')
	-- RequestIpl('hei_carrier_lodlights')
	-- RequestIpl('hei_carrier_slod')
	RequestIpl('hei_yacht_heist')
	RequestIpl('hei_yacht_heist_Bar')
	RequestIpl('hei_yacht_heist_Bedrm')
	RequestIpl('hei_yacht_heist_Bridge')
	RequestIpl('hei_yacht_heist_DistantLights')
	RequestIpl('hei_yacht_heist_enginrm')
	RequestIpl('hei_yacht_heist_LODLights')
	RequestIpl('hei_yacht_heist_Lounge')
	RequestIpl('hei_sm_16_interior_v_bahama_milo_')
	RequestIpl('redCarpet')
	RequestIpl('ex_dt1_02_office_01b')
	RequestIpl('ex_dt1_11_office_01b')
	RequestIpl('ex_sm_13_office_01b')
	RequestIpl('ex_sm_15_office_01b')
	RequestIpl('apa_v_mp_h_01_a')
	RequestIpl('apa_v_mp_h_02_c')
	RequestIpl('apa_v_mp_h_04_b')
	RequestIpl('bkr_biker_interior_placement_interior_0_biker_dlc_int_01_milo')
	RequestIpl('bkr_biker_interior_placement_interior_1_biker_dlc_int_02_milo')
	RequestIpl('bkr_biker_interior_placement_interior_2_biker_dlc_int_ware01_milo')
	RequestIpl('bkr_biker_interior_placement_interior_2_biker_dlc_int_ware02_milo')
	RequestIpl('bkr_biker_interior_placement_interior_2_biker_dlc_int_ware03_milo')
	RequestIpl('bkr_biker_interior_placement_interior_2_biker_dlc_int_ware04_milo')
	RequestIpl('bkr_biker_interior_placement_interior_2_biker_dlc_int_ware05_milo')
	RequestIpl('bkr_biker_interior_placement_interior_3_biker_dlc_int_ware02_milo')
	RequestIpl('bkr_biker_interior_placement_interior_4_biker_dlc_int_ware03_milo')
	RequestIpl('bkr_biker_interior_placement_interior_5_biker_dlc_int_ware04_milo')
	RequestIpl('bkr_biker_interior_placement_interior_6_biker_dlc_int_ware05_milo')
	RequestIpl('ex_exec_warehouse_placement_interior_1_int_warehouse_s_dlc_milo')
	RequestIpl('ex_exec_warehouse_placement_interior_0_int_warehouse_m_dlc_milo')
	RequestIpl('ex_exec_warehouse_placement_interior_2_int_warehouse_l_dlc_milo')
	RequestIpl('imp_impexp_interior_placement')
	RequestIpl('imp_impexp_interior_placement_interior_0_impexp_int_01_milo_')
	RequestIpl('imp_impexp_interior_placement_interior_1_impexp_intwaremed_milo_')
	RequestIpl('imp_impexp_interior_placement_interior_2_imptexp_mod_int_01_milo_')
	RequestIpl('imp_impexp_interior_placement_interior_3_impexp_int_02_milo_')
	RequestIpl("ex_exec_warehouse_placement_interior_0_int_warehouse_m_dlc_milo_")
	RequestIpl("ex_exec_warehouse_placement_interior_1_int_warehouse_s_dlc_milo_")
	RequestIpl("ex_exec_warehouse_placement_interior_2_int_warehouse_l_dlc_milo")
	RequestIpl('imp_dt1_02_modgarage')
	RequestIpl('imp_dt1_02_cargarage_a')
	RequestIpl('imp_dt1_02_cargarage_b')
	RequestIpl('imp_dt1_02_cargarage_c')
	RequestIpl('imp_dt1_11_modgarage')
	RequestIpl('imp_dt1_11_cargarage_a')
	RequestIpl('imp_dt1_11_cargarage_b')
	RequestIpl('imp_dt1_11_cargarage_c')
	RequestIpl('imp_sm_13_modgarage')
	RequestIpl('imp_sm_13_cargarage_a')
	RequestIpl('imp_sm_13_cargarage_b')
	RequestIpl('imp_sm_13_cargarage_c')
	RequestIpl('imp_sm_15_modgarage')
	RequestIpl('imp_sm_15_cargarage_a')
	RequestIpl('imp_sm_15_cargarage_b')
	RequestIpl('imp_sm_15_cargarage_c')
	RequestIpl('gr_case0_bunkerclosed')
	RequestIpl('gr_case1_bunkerclosed')
	RequestIpl('gr_case2_bunkerclosed')
	RequestIpl('gr_case3_bunkerclosed')
	RequestIpl('gr_case4_bunkerclosed')
	RequestIpl('gr_case5_bunkerclosed')
	RequestIpl('gr_case6_bunkerclosed')
	RequestIpl('gr_case7_bunkerclosed')
	RequestIpl('gr_case9_bunkerclosed')
	RequestIpl('gr_case10_bunkerclosed')
	RequestIpl('gr_case11_bunkerclosed')
	RequestIpl('xm_siloentranceclosed_x17')
	RequestIpl('sm_smugdlc_interior_placement')
	RequestIpl('sm_smugdlc_interior_placement_interior_0_smugdlc_int_01_milo_')
	RequestIpl('xm_x17dlc_int_placement')
	RequestIpl('xm_x17dlc_int_placement_interior_0_x17dlc_int_base_ent_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_1_x17dlc_int_base_loop_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_2_x17dlc_int_bse_tun_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_3_x17dlc_int_base_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_4_x17dlc_int_facility_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_5_x17dlc_int_facility2_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_6_x17dlc_int_silo_01_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_7_x17dlc_int_silo_02_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_8_x17dlc_int_sub_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_9_x17dlc_int_01_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_10_x17dlc_int_tun_straight_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_11_x17dlc_int_tun_slope_flat_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_12_x17dlc_int_tun_flat_slope_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_13_x17dlc_int_tun_30d_r_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_14_x17dlc_int_tun_30d_l_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_15_x17dlc_int_tun_straight_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_16_x17dlc_int_tun_straight_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_17_x17dlc_int_tun_slope_flat_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_18_x17dlc_int_tun_slope_flat_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_19_x17dlc_int_tun_flat_slope_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_20_x17dlc_int_tun_flat_slope_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_21_x17dlc_int_tun_30d_r_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_22_x17dlc_int_tun_30d_r_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_23_x17dlc_int_tun_30d_r_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_24_x17dlc_int_tun_30d_r_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_25_x17dlc_int_tun_30d_l_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_26_x17dlc_int_tun_30d_l_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_27_x17dlc_int_tun_30d_l_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_28_x17dlc_int_tun_30d_l_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_29_x17dlc_int_tun_30d_l_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_30_v_apart_midspaz_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_31_v_studio_lo_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_32_v_garagem_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_33_x17dlc_int_02_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_34_x17dlc_int_lab_milo_')
	RequestIpl('xm_x17dlc_int_placement_interior_35_x17dlc_int_tun_entry_milo_')
	RequestIpl('xm_x17dlc_int_placement_strm_0')
	RequestIpl('xm_bunkerentrance_door')
	RequestIpl('xm_hatch_01_cutscene')
	RequestIpl('xm_hatch_02_cutscene')
	RequestIpl('xm_hatch_03_cutscene')
	RequestIpl('xm_hatch_04_cutscene')
	RequestIpl('xm_hatch_06_cutscene')
	RequestIpl('xm_hatch_07_cutscene')
	RequestIpl('xm_hatch_08_cutscene')
	RequestIpl('xm_hatch_09_cutscene')
	RequestIpl('xm_hatch_10_cutscene')
	RequestIpl('xm_hatch_closed')
	RequestIpl('xm_hatches_terrain')
	RequestIpl('xm_hatches_terrain_lod')
	RequestIpl('xm_mpchristmasadditions')
	RequestIpl("DT1_05_HC_REMOVE")
	RequestIpl("ferris_finale_anim")
	RequestIpl("ferris_finale_anim_lod")
	RequestIpl('ba_barriers_case1')
	RequestIpl('ba_case1_madonna')
	
	SetStaticEmitterEnabled('SE_ba_dlc_club_exterior', false)
	SetStaticEmitterEnabled('SE_ba_dlc_int_01_Bogs', false)
	SetStaticEmitterEnabled('SE_ba_dlc_int_01_Entry_Hall', false)
	SetStaticEmitterEnabled('SE_ba_dlc_int_01_Entry_Stairs', false)
	SetStaticEmitterEnabled('SE_ba_dlc_int_01_garage', false)
	SetStaticEmitterEnabled('SE_ba_dlc_int_01_main_area', false)
	SetStaticEmitterEnabled('SE_ba_dlc_int_01_main_area_2', false)
	SetStaticEmitterEnabled('SE_ba_dlc_int_01_office', false)
	SetStaticEmitterEnabled('SE_ba_dlc_int_01_rear_L_corridor', false)
	SetStaticEmitterEnabled('LOS_SANTOS_VANILLA_UNICORN_01_STAGE', false)
	SetStaticEmitterEnabled('LOS_SANTOS_VANILLA_UNICORN_02_MAIN_ROOM', false)
	SetStaticEmitterEnabled('LOS_SANTOS_VANILLA_UNICORN_03_BACK_ROOM', false)
	SetStaticEmitterEnabled('LOS_SANTOS_AMMUNATION_GUN_RANGE', false)
	SetStaticEmitterEnabled('LOS_SANTOS_AMMUNATION_GUN_RANGE_01', false)
	SetStaticEmitterEnabled('LOS_SANTOS_AMMUNATION_GUN_RANGE_02', false)
	SetStaticEmitterEnabled('LOS_SANTOS_AMMUNATION_GUN_RANGE_03', false)
	SetScenarioTypeEnabled("WORLD_MOUNTAIN_LION_REST", true)
	SetScenarioTypeEnabled("WORLD_MOUNTAIN_LION_WANDER", true)
	-- SetScenarioTypeEnabled("WORLD_VEHICLE_STREETRACE", false)
	-- SetScenarioTypeEnabled("WORLD_VEHICLE_SALTON_DIRT_BIKE", false)
	-- SetScenarioTypeEnabled("WORLD_VEHICLE_SALTON", false)
	-- SetScenarioTypeEnabled("WORLD_VEHICLE_POLICE_NEXT_TO_CAR", false)
	-- SetScenarioTypeEnabled("WORLD_VEHICLE_POLICE_CAR", false)
	-- SetScenarioTypeEnabled("WORLD_VEHICLE_POLICE_BIKE", false)
	-- SetScenarioTypeEnabled("WORLD_VEHICLE_MILITARY_PLANES_SMALL", false)
	-- SetScenarioTypeEnabled("WORLD_VEHICLE_MILITARY_PLANES_BIG", false)
	-- SetScenarioTypeEnabled("WORLD_VEHICLE_MECHANIC", false)
	-- SetScenarioTypeEnabled("WORLD_VEHICLE_EMPTY", false)
	-- SetScenarioTypeEnabled("WORLD_VEHICLE_BUSINESSMEN", false)
	-- SetScenarioTypeEnabled("WORLD_VEHICLE_BIKE_OFF_ROAD_RACE", false)

	RequestIpl("vw_casino_penthouse")
	RequestIpl("hei_dlc_windows_casino")
	local InteriorId = GetInteriorAtCoords(976.63, 70.29, 115.16)     
	ActivateInteriorEntitySet(InteriorId, "set_pent_tint_shell")
	SetInteriorEntitySetColor(InteriorId, "set_pent_tint_shell", 1)
	ActivateInteriorEntitySet(InteriorId, "set_pent_media_bar_open")
	SetInteriorEntitySetColor(InteriorId, "set_pent_media_bar_open", 1)
	ActivateInteriorEntitySet(InteriorId, "set_pent_spa_bar_open")
	SetInteriorEntitySetColor(InteriorId, "set_pent_spa_bar_open", 1)
	ActivateInteriorEntitySet(InteriorId, "set_pent_dealer")
	SetInteriorEntitySetColor(InteriorId, "set_pent_dealer", 1)
	ActivateInteriorEntitySet(InteriorId, "set_pent_pattern_04")
	SetInteriorEntitySetColor(InteriorId, "set_pent_pattern_04", 1)
	ActivateInteriorEntitySet(InteriorId, "set_pent_arcade_retro")
	ActivateInteriorEntitySet(InteriorId, "set_pent_clutter_03")
	ActivateInteriorEntitySet(InteriorId, "set_pent_clutter_01")
	ActivateInteriorEntitySet(InteriorId, "set_pent_bar_clutter")
	ActivateInteriorEntitySet(InteriorId, "set_pent_bar_light_01")
	ActivateInteriorEntitySet(InteriorId, "set_pent_bar_party_1")   
	RefreshInterior(InteriorId)

	RequestIpl('shr_int')
	local InteriorId = GetInteriorAtCoords(-46.16, -1097.52, 26.42)
	LoadInterior(InteriorId)
	EnableInteriorProp(InteriorId, 'csr_beforeMission')
	RefreshInterior(InteriorId)

	-- Nightclub
	RequestIpl('ba_barriers_case1')
	RequestIpl('ba_case1_madonna')
	RequestIpl("ba_int_placement_ba_interior_2_dlc_int_03_ba_milo_")
	local interiorID = GetInteriorAtCoords(-1589.72, -3012.38, -79.00)
	EnableInteriorProp(interiorID, 'Int01_ba_clubname_01') 
	EnableInteriorProp(interiorID, 'Int01_ba_Style02') 
	EnableInteriorProp(interiorID, 'Int01_ba_style02_podium') 
	EnableInteriorProp(interiorID, 'Int01_ba_dj04') 
	EnableInteriorProp(interiorID, 'Int01_ba_equipment_upgrade') 
	EnableInteriorProp(interiorID, 'Int01_ba_security_upgrade')  
	EnableInteriorProp(interiorID, 'DJ_04_Lights_02')
	EnableInteriorProp(interiorID, 'Int01_ba_trad_lights') 
	EnableInteriorProp(interiorID, 'Int01_ba_trophy03') 
	EnableInteriorProp(interiorID, 'Int01_ba_deliverytruck')
	EnableInteriorProp(interiorID, 'Int01_ba_trophy04')
	EnableInteriorProp(interiorID, 'Int01_ba_trophy05')
	EnableInteriorProp(interiorID, 'Int01_ba_trophy07')
	EnableInteriorProp(interiorID, 'Int01_ba_trophy08')
	EnableInteriorProp(interiorID, 'Int01_ba_trophy09')
	EnableInteriorProp(interiorID, 'Int01_ba_trophy10')
	EnableInteriorProp(interiorID, 'Int01_ba_trophy11')
	EnableInteriorProp(interiorID, 'Int01_ba_dry_ice')
	RefreshInterior(interiorID)
	
	SetStaticEmitterEnabled('SE_ba_dlc_club_exterior', false)
	SetStaticEmitterEnabled('SE_ba_dlc_int_01_Bogs', false)
	SetStaticEmitterEnabled('SE_ba_dlc_int_01_Entry_Hall', false)
	SetStaticEmitterEnabled('SE_ba_dlc_int_01_Entry_Stairs', false)
	SetStaticEmitterEnabled('SE_ba_dlc_int_01_garage', false)
	SetStaticEmitterEnabled('SE_ba_dlc_int_01_main_area', false)
	SetStaticEmitterEnabled('SE_ba_dlc_int_01_main_area_2', false)
	SetStaticEmitterEnabled('SE_ba_dlc_int_01_office', false)
	SetStaticEmitterEnabled('SE_ba_dlc_int_01_rear_L_corridor', false)
	SetStaticEmitterEnabled('LOS_SANTOS_VANILLA_UNICORN_01_STAGE', false)
	SetStaticEmitterEnabled('LOS_SANTOS_VANILLA_UNICORN_02_MAIN_ROOM', false)
	SetStaticEmitterEnabled('LOS_SANTOS_VANILLA_UNICORN_03_BACK_ROOM', false)
	RefreshInterior(interiorID)

	-- Hospital
	RequestIpl("rc12b_hospitalinterior")
	RequestIpl("rc12b_hospitalinterior_lod")
	RequestIpl("rc12b_default")
	local interiorID = GetInteriorAtCoords(356.8, -590.1, 43.3)
	RefreshInterior(interiorID)

    RequestIpl('gabz_biker_interior_placement_interior_2_biker_dlc_int_ware01_milo_')
    local interiorID = GetInteriorAtCoords(1061.14, -2318.54, 19.72)
    EnableInteriorProp(interiorID, "gabz_meth_lab_basic")
    EnableInteriorProp(interiorID, "gabz_meth_lab_low")
    RefreshInterior(interiorID)

	RequestIpl("bkr_biker_interior_placement_interior_0_biker_dlc_int_01_milo")
	local InteriorId = GetInteriorAtCoords(114.9445, 3618.368, 39.68667)
	EnableInteriorProp(InteriorId, "walls_01")
	EnableInteriorProp(InteriorId, "furnishings_02")
	EnableInteriorProp(InteriorId, "decorative_02")
	EnableInteriorProp(InteriorId, "mural_01")
	EnableInteriorProp(InteriorId, "gun_locker")
	EnableInteriorProp(InteriorId, "mod_booth")
	EnableInteriorProp(InteriorId, "cash_stash1")
	RefreshInterior(InteriorId)
	
	-- local InteriorId = 258561
	-- RequestIpl("grdlc_int_01_shell")
	-- RequestIpl("gr_grdlc_int_01")
	-- RequestIpl("gr_grdlc_int_02")
	-- RequestIpl("gr_entrance_placement")
	-- RequestIpl("gr_grdlc_interior_placement")
	-- RequestIpl("gr_grdlc_interior_placement_interior_0_grdlc_int_01_milo_")
	-- RequestIpl("gr_grdlc_interior_placement_interior_1_grdlc_int_02_milo_")
	-- EnableInteriorProp(InteriorId, "bunker_style_b")
	-- EnableInteriorProp(InteriorId, "upgrade_bunker_set")
	-- EnableInteriorProp(InteriorId, "upgrade_bunker_set_more")
	-- EnableInteriorProp(InteriorId, "security_upgrade")
	-- EnableInteriorProp(InteriorId, "Office_Upgrade_set")
	-- EnableInteriorProp(InteriorId, "gun_range_lights")
	-- EnableInteriorProp(InteriorId, "gun_schematic_set")
	-- EnableInteriorProp(InteriorId, "gun_locker_upgrade")
	-- RefreshInterior(InteriorId)
end)