Shared = {}

local StringCharset = {}
local NumberCharset = {}

for i = 48,  57 do table.insert(NumberCharset, string.char(i)) end
for i = 65,  90 do table.insert(StringCharset, string.char(i)) end
for i = 97, 122 do table.insert(StringCharset, string.char(i)) end

Shared.RandomStr = function(Length)
	if Length > 0 then
		return Shared.RandomStr(Length - 1)..StringCharset[math.random(1, #StringCharset)]
	else
		return ''
	end
end

Shared.RandomInt = function(Length)
	if Length > 0 then
		return Shared.RandomInt(Length - 1)..NumberCharset[math.random(1, #NumberCharset)]
	else
		return ''
	end
end

Shared.Tax = {
    ['Property'] = 15, -- +15% of the price
    ['Vehicle'] = 49, -- +49% of the price
    ['Goods'] = 15, -- +15% of the price
    ['Clothes'] = 15, -- +15% of the prices,
    ['Gas'] = 17, -- +17% of the price
}

Shared.Groups = {
    ['user'] = 'User',
    ['admin'] = 'Admin',
    ['god'] = 'God'
}

Shared.Cryptos = {
    ['shungite'] = {
        ['CryptoId'] = 2,
        ['Icon'] = '<i class="fas fa-caret-square-up"></i>',
        ['Label'] = 'Shungite',
        ['Name'] = 'shungite',
        ['Short'] = 'sge',
        ['Worth'] = 2.00,
        ['Purcashable'] = true,
        ['Exchangable'] = true,
    },
    ['guinea'] = {
        ['CryptoId'] = 1,
        ['Icon'] = '<i class="fas fa-horse-head"></i>',
        ['Label'] = 'Guinea',
        ['Name'] = 'guinea',
        ['Short'] = 'gne',
        ['Worth'] = 2.00,
        ['Purcashable'] = true,
        ['Exchangable'] = true,
    },
}

Shared.Jobs = {
    ['unemployed'] = {
        Name = 'unemployed',
        Label = 'Unemployed',
        Salary = 10,
        Duty = false,
        Student = false,
        HighCommand = false
    },
    ['police'] = {
        Name = 'police',
        Label = 'Police',
        Salary = 145,
        Duty = false,
        Callsign = 'XXX',
        Student = false,
        Department = 'LSPD',
        HighCommand = false
    },
    ['ems'] = {
        Name = 'ems',
        Label = 'EMS',
        Salary = 145,
        Duty = false,
        Callsign = 'XXX',
        Student = false,
        HighCommand = false
    },
    ['judge'] = {
        Name = 'judge',
        Label = 'Judge',
        Salary = 200,
        Duty = false,
        Student = false,
        HighCommand = false,
    },
    ['lawyer'] = {
        Name = 'lawyer',
        Label = 'Lawyer',
        Salary = 50,
        Duty = false,
    },
    ['prosecutor'] = {
        Name = 'prosecutor',
        Label = 'Prosecutor',
        Salary = 50,
        Duty = false,
    },
    ['realestate'] = {
        Name = 'realestate',
        Label = 'Real Estate',
        Salary = 50,
        Duty = false,
    },
}

Shared.JobDepartments = {
    ['police'] = {'BCSO', 'LSPD', 'SASP'}
}

Shared.VehicleMods = {
    ['ModSpoilers'] = 0,
    ['ModFrontBumper'] = 1,
    ['ModRearBumper'] = 2,
    ['ModSideSkirt'] = 3,
    ['ModExhaust'] = 4,
    ['ModFrame'] = 5,
    ['ModGrille'] = 6,
    ['ModHood'] = 7,
    ['ModFender'] = 8,
    ['ModRightFender'] = 9,
    ['ModRoof'] = 10,
    ['ModEngine'] = 11,
    ['ModBrakes'] = 12,
    ['ModTransmission'] = 13,
    ['ModHorns'] = 14,
    ['ModSuspension'] = 15,
    ['ModArmor'] = 16,
    ['ModTurbo'] = 18,
    ['ModXenon'] = 22,
    ['ModFrontWheels'] = 23,
    ['ModBackWheels'] = 24,
    ['ModPlateHolder'] = 25,
    ['ModVanityPlate'] = 26,
    ['ModTrimA'] = 27,
    ['ModOrnaments'] = 28,
    ['ModDashboard'] = 29,
    ['ModDial'] = 30,
    ['ModDoorSpeaker'] = 31,
    ['ModSeats'] = 32,
    ['ModSteeringWheel'] = 33,
    ['ModShifterLeavers'] = 34,
    ['ModAPlate'] = 35,
    ['ModSpeakers'] = 36,
    ['ModTrunk'] = 37,
    ['ModHydrolic'] = 38,
    ['ModEngineBlock'] = 39,
    ['ModAirFilter'] = 40,
    ['ModStruts'] = 41,
    ['ModArchCover'] = 42,
    ['ModAerials'] = 43,
    ['ModTrimB'] = 44,
    ['ModTank'] = 45,
    ['ModWindows'] = 46,
    ['ModLivery'] = 48,
}

Shared.Weapons = {
    [GetHashKey('weapon_taser')] = {
        ['WeaponID'] = 'weapon_taser',  
        ['AmmoType'] = 'AMMO_TASER',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 1,
    },
    [GetHashKey('weapon_paintball')] = {
        ['WeaponID'] = 'weapon_paintball',  
        ['AmmoType'] = 'AMMO_PAINTBALL',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 200,
    },
    [GetHashKey('weapon_beretta')] = {
        ['WeaponID'] = 'weapon_beretta',  
        ['AmmoType'] = 'AMMO_PISTOL',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 50,
    },
    [GetHashKey('weapon_colt')] = {
        ['WeaponID'] = 'weapon_colt',   
        ['AmmoType'] = 'AMMO_PISTOL',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 50,
    },
    [GetHashKey('weapon_glock')] = {
        ['WeaponID'] = 'weapon_glock',   
        ['AmmoType'] = 'AMMO_PISTOL',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 50,
    },
    [GetHashKey('weapon_waltherp99')] = {
        ['WeaponID'] = 'weapon_waltherp99',   
        ['AmmoType'] = 'AMMO_PISTOL',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 100,
    },
    [GetHashKey('weapon_glock18c')] = {
        ['WeaponID'] = 'weapon_glock18c',   
        ['AmmoType'] = 'AMMO_PISTOL',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 50,
    },
    [GetHashKey('weapon_browning')] = {
        ['WeaponID'] = 'weapon_browning',   
        ['AmmoType'] = 'AMMO_PISTOL',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 50,
    },
    [GetHashKey('weapon_python')] = {
        ['WeaponID'] = 'weapon_python',   
        ['AmmoType'] = 'AMMO_REVOLVER',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 24,
    },
    [GetHashKey('weapon_diamond')] = {
        ['WeaponID'] = 'weapon_diamond',   
        ['AmmoType'] = 'AMMO_PISTOL',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 50,
    },
    [GetHashKey('weapon_heavypistol')] = {
        ['WeaponID'] = 'weapon_heavypistol',   
        ['AmmoType'] = 'AMMO_PISTOL',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 50,
    },
    [GetHashKey('weapon_appistol')] = {
        ['WeaponID'] = 'weapon_appistol',   
        ['AmmoType'] = 'AMMO_PISTOL',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('weapon_mac10')] = {
        ['WeaponID'] = 'weapon_mac10',  
        ['AmmoType'] = 'AMMO_SMG',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('weapon_uzi')] = {
        ['WeaponID'] = 'weapon_uzi',    
        ['AmmoType'] = 'AMMO_SMG',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('weapon_draco')] = {
        ['WeaponID'] = 'weapon_draco',    
        ['AmmoType'] = 'AMMO_SMG',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('weapon_mpx')] = {
        ['WeaponID'] = 'weapon_mpx',    
        ['AmmoType'] = 'AMMO_SMG',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('weapon_m4')] = {
        ['WeaponID'] = 'weapon_m4',     
        ['AmmoType'] = 'AMMO_RIFLE',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('weapon_scar')] = {
        ['WeaponID'] = 'weapon_scar',     
        ['AmmoType'] = 'AMMO_RIFLE',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('weapon_groza')] = {
        ['WeaponID'] = 'weapon_groza',    
        ['AmmoType'] = 'AMMO_RIFLE',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('weapon_m70')] = {
        ['WeaponID'] = 'weapon_m70',    
        ['AmmoType'] = 'AMMO_RIFLE',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('weapon_ak47')] = {
        ['WeaponID'] = 'weapon_ak47',   
        ['AmmoType'] = 'AMMO_RIFLE',
        ['SelectFire'] = true,
        ['MaxAmmo'] = 120,
    },
    [GetHashKey('weapon_remington')] = {
        ['WeaponID'] = 'weapon_remington',   
        ['AmmoType'] = 'AMMO_SHOTGUN',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 24,
    },
    [GetHashKey('weapon_rubberslug')] = {
        ['WeaponID'] = 'weapon_rubberslug',   
        ['AmmoType'] = 'AMMO_RUBBER_SHOTGUN',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 20,
    },
    [GetHashKey('weapon_sniperrifle2')] = {
        ['WeaponID'] = 'weapon_sniperrifle2',   
        ['AmmoType'] = 'AMMO_SNIPER',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 12,
    },
    [GetHashKey('weapon_empgun')] = {
        ['WeaponID'] = 'weapon_empgun',  
        ['AmmoType'] = 'AMMO_EMP',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 5,
    },
    -- Weapon : Melee
    [GetHashKey('weapon_flashlight')] = {
        ['WeaponID'] = 'weapon_flashlight',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.4,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_switchblade')] = {
        ['WeaponID'] = 'weapon_switchblade',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.2,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_gavel')] = {
        ['WeaponID'] = 'weapon_gavel',
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.2,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_shiv')] = {
        ['WeaponID'] = 'weapon_shiv',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.2,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_shoe')] = {
        ['WeaponID'] = 'weapon_shoe',
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.01,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_sledgeham')] = {
        ['WeaponID'] = 'weapon_sledgeham',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.5,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_nightstick')] = {
        ['WeaponID'] = 'weapon_nightstick',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.3,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_hammer')] = {
        ['WeaponID'] = 'weapon_hammer',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.3,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_knife')] = {
        ['WeaponID'] = 'weapon_knife',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.3,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_hatchet')] = {
        ['WeaponID'] = 'weapon_hatchet',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.5,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_wrench')] = {
        ['WeaponID'] = 'weapon_wrench',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.3,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_machete')] = {
        ['WeaponID'] = 'weapon_machete',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.5,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_bottle')] = {
        ['WeaponID'] = 'weapon_bottle',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.3,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_bat')] = {
        ['WeaponID'] = 'weapon_bat',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.3,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_knuckle')] = {
        ['WeaponID'] = 'weapon_knuckle',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.25,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_katana')] = {
        ['WeaponID'] = 'weapon_katana',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.5,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_crutch')] = {
        ['WeaponID'] = 'weapon_crutch',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.2,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_unicorn')] = {
        ['WeaponID'] = 'weapon_unicorn',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.1,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_unarmed')] = {
        ['WeaponID'] = 'weapon_unarmed',  
        ['AmmoType'] = 'AMMO_NONE',
        ['SelectFire'] = false,
        ['Modifier'] = 0.2,
        ['MaxAmmo'] = 0,
    },
    -- Weapon : Explosive
    [GetHashKey('weapon_grenade')] = {
        ['WeaponID'] = 'weapon_grenade',  
        ['AmmoType'] = 'AMMO_FIRE',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_stickybomb')] = {
        ['WeaponID'] = 'weapon_stickybomb',  
        ['AmmoType'] = 'AMMO_FIRE',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_smokegrenade')] = {
        ['WeaponID'] = 'weapon_stickybomb',  
        ['AmmoType'] = 'AMMO_FIRE',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_flare')] = {
        ['WeaponID'] = 'weapon_flare',  
        ['AmmoType'] = 'AMMO_FIRE',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 0,
    },
    [GetHashKey('weapon_molotov')] = {
        ['WeaponID'] = 'weapon_molotov',  
        ['AmmoType'] = 'AMMO_FIRE',
        ['SelectFire'] = false,
        ['MaxAmmo'] = 0,
    },
}

--[[
    Icon Types:
    Car
    Motorcycle
    Truck
    Bicycle
    Van
]]

Shared.Vehicles = {
    -- Cycle
    [GetHashKey('bimx')] = {
        ['Vehicle'] = 'bimx',
        ['Model'] = 'Pedal',
        ['Name'] = 'BMX (Mod)',
        ['ShopClass'] = 'Cycle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Bicycle',
        ['Price'] = 750,
        ['CanBoost'] = false,
    },
    [GetHashKey('bmx')] = {
        ['Vehicle'] = 'bmx',
        ['Model'] = 'Pedal',
        ['Name'] = 'BMX',
        ['ShopClass'] = 'Cycle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Bicycle',
        ['Price'] = 450,
        ['CanBoost'] = false,
    },
    [GetHashKey('cruiser')] = {
        ['Vehicle'] = 'cruiser',
        ['Model'] = 'Pedal',
        ['Name'] = 'Cruiser',
        ['ShopClass'] = 'Cycle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Bicycle',
        ['Price'] = 250,
        ['CanBoost'] = false,
    },
    [GetHashKey('scorcher')] = {
        ['Vehicle'] = 'scorcher',
        ['Model'] = 'Pedal',
        ['Name'] = 'Scorcher',
        ['ShopClass'] = 'Cycle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Bicycle',
        ['Price'] = 750,
        ['CanBoost'] = false,
    },
    -- Compacts
    [GetHashKey('asbo')] = {
        ['Vehicle'] = 'asbo',
        ['Model'] = 'Maxwell',
        ['Name'] = 'Asbo',
        ['ShopClass'] = 'Compacts',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 36550,
        ['CanBoost'] = true,
    },
    [GetHashKey('blista')] = {
        ['Vehicle'] = 'blista',
        ['Model'] = 'Dinka',
        ['Name'] = 'Blista',
        ['ShopClass'] = 'Compacts',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 33500,
        ['CanBoost'] = true,
    },
    [GetHashKey('brioso')] = {
        ['Vehicle'] = 'brioso',
        ['Model'] = 'Grotti',
        ['Name'] = 'Brioso',
        ['ShopClass'] = 'Compacts',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 36500,
        ['CanBoost'] = true,
    },
    [GetHashKey('brioso2')] = {
        ['Vehicle'] = 'brioso2',
        ['Model'] = 'Grotti',
        ['Name'] = 'Brioso 300',
        ['ShopClass'] = 'Compacts',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 38500,
        ['CanBoost'] = true,
    },
    [GetHashKey('rhapsody')] = {
        ['Vehicle'] = 'rhapsody',
        ['Model'] = 'Declasse',
        ['Name'] = 'Rhapsody',
        ['ShopClass'] = 'Compacts',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 35500,
        ['CanBoost'] = true,
    },
    [GetHashKey('prairie')] = {
        ['Vehicle'] = 'prairie',
        ['Model'] = 'Bollokan',
        ['Name'] = 'Prairie',
        ['ShopClass'] = 'Compacts',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 34500,
        ['CanBoost'] = true,
    },
    [GetHashKey('kanjo')] = {
        ['Vehicle'] = 'kanjo',
        ['Model'] = 'Dinka',
        ['Name'] = 'Blista Kanjo',
        ['ShopClass'] = 'Compacts',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 36550,
        ['CanBoost'] = true,
    },
    [GetHashKey('panto')] = {
        ['Vehicle'] = 'panto',
        ['Model'] = 'Benefactor',
        ['Name'] = 'Panto',
        ['ShopClass'] = 'Compacts',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 27550,
        ['CanBoost'] = true,
    },
    [GetHashKey('weevil')] = {
        ['Vehicle'] = 'weevil',
        ['Model'] = 'BF',
        ['Name'] = 'Weevil',
        ['ShopClass'] = 'Compacts',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 37450,
        ['CanBoost'] = true,
    },
    [GetHashKey('dynasty')] = {
        ['Vehicle'] = 'dynasty',
        ['Model'] = 'Weeny',
        ['Name'] = 'Dynasty',
        ['ShopClass'] = 'Compacts',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 38550,
        ['CanBoost'] = true,
    },
    -- Motorcycles
    [GetHashKey('akuma')] = {
        ['Vehicle'] = 'akuma',
        ['Model'] = 'Dinka',
        ['Name'] = 'Akuma',
        ['ShopClass'] = 'Motorcycle',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Motorcycle',
        ['Price'] = 45500,
        ['CanBoost'] = true,
    },
    [GetHashKey('bagger')] = {
        ['Vehicle'] = 'bagger',
        ['Model'] = 'Western Motorcycle Company',
        ['Name'] = 'Bagger',
        ['ShopClass'] = 'Motorcycle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Motorcycle',
        ['Price'] = 35000,
        ['CanBoost'] = true,
    },
    [GetHashKey('bati')] = {
        ['Vehicle'] = 'bati',
        ['Model'] = 'Pegassi',
        ['Name'] = 'Bati 801',
        ['ShopClass'] = 'Motorcycle',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Motorcycle',
        ['Price'] = 35000,
        ['CanBoost'] = true,
    },
    [GetHashKey('bf400')] = {
        ['Vehicle'] = 'bf400',
        ['Model'] = 'Nagasaki',
        ['Name'] = 'BF-400',
        ['ShopClass'] = 'Motorcycle',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Motorcycle',
        ['Price'] = 45500,
        ['CanBoost'] = true,
    },
    [GetHashKey('cliffhanger')] = {
        ['Vehicle'] = 'cliffhanger',
        ['Model'] = 'Western Motorcycle Company',
        ['Name'] = 'Cliffhanger',
        ['ShopClass'] = 'Motorcycle',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Motorcycle',
        ['Price'] = 38450,
        ['CanBoost'] = true,
    },
    [GetHashKey('daemon')] = {
        ['Vehicle'] = 'daemon',
        ['Model'] = 'Western Motorcycle Company',
        ['Name'] = 'Daemon',
        ['ShopClass'] = 'Motorcycle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Motorcycle',
        ['Price'] = 35000,
        ['CanBoost'] = true,
    },
    [GetHashKey('avarus')] = {
        ['Vehicle'] = 'avarus',
        ['Model'] = 'Liberty City Cycles',
        ['Name'] = 'Avarus',
        ['ShopClass'] = 'Motorcycle',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Motorcycle',
        ['Price'] = 50000,
        ['CanBoost'] = false,
    },
    [GetHashKey('sanchez')] = {
        ['Vehicle'] = 'sanchez',
        ['Model'] = 'Maibatsu',
        ['Name'] = 'Sanchez',
        ['ShopClass'] = 'Motorcycle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Motorcycle',
        ['Price'] = 45000,
        ['CanBoost'] = true,
    },
    [GetHashKey('double')] = {
        ['Vehicle'] = 'double',
        ['Model'] = 'Dinka',
        ['Name'] = 'Double T',
        ['ShopClass'] = 'Motorcycle',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Motorcycle',
        ['Price'] = 51500,
        ['CanBoost'] = true,
    },
    [GetHashKey('faggio')] = {
        ['Vehicle'] = 'faggio',
        ['Model'] = 'Pegassi',
        ['Name'] = 'Faggio Sport',
        ['ShopClass'] = 'Motorcycle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Motorcycle',
        ['Price'] = 5500,
        ['CanBoost'] = false,
    },
    [GetHashKey('faggio2')] = {
        ['Vehicle'] = 'faggio2',
        ['Model'] = 'Pegassi',
        ['Name'] = 'Faggio City',
        ['ShopClass'] = 'Motorcycle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Motorcycle',
        ['Price'] = 9500,
        ['CanBoost'] = false,
    },
    -- Muscle
    [GetHashKey('blade')] = {
        ['Vehicle'] = 'blade',
        ['Model'] = 'Vapid',
        ['Name'] = 'Blade',
        ['ShopClass'] = 'Muscle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 40000,
        ['CanBoost'] = true,
    },
    [GetHashKey('buccaneer')] = {
        ['Vehicle'] = 'buccaneer',
        ['Model'] = 'Albany',
        ['Name'] = 'Buccaneer',
        ['ShopClass'] = 'Muscle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 39500,
        ['CanBoost'] = true,
    },
    [GetHashKey('chino')] = {
        ['Vehicle'] = 'chino',
        ['Model'] = 'Vapid',
        ['Name'] = 'Chino',
        ['ShopClass'] = 'Muscle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 41000,
        ['CanBoost'] = true,
    },
    [GetHashKey('coquette3')] = {
        ['Vehicle'] = 'coquette3',
        ['Model'] = 'Invetero',
        ['Name'] = 'Coquette Classic',
        ['ShopClass'] = 'Muscle',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 45500,
        ['CanBoost'] = true,
    },
    [GetHashKey('dominator')] = {
        ['Vehicle'] = 'dominator',
        ['Model'] = 'Vapid',
        ['Name'] = 'Dominator',
        ['ShopClass'] = 'Muscle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 42500,
        ['CanBoost'] = true,
    },
    [GetHashKey('dominator3')] = {
        ['Vehicle'] = 'dominator3',
        ['Model'] = 'Vapid',
        ['Name'] = 'Dominator GTX',
        ['ShopClass'] = 'Muscle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 58500,
        ['CanBoost'] = true,
    },
    [GetHashKey('dukes')] = {
        ['Vehicle'] = 'dukes',
        ['Model'] = 'Imponte',
        ['Name'] = 'dukes',
        ['ShopClass'] = 'Muscle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 37500,
        ['CanBoost'] = true,
    },
    [GetHashKey('virgo2')] = {
        ['Vehicle'] = 'virgo2',
        ['Model'] = 'Dundreary',
        ['Name'] = 'Virgo',
        ['ShopClass'] = 'Muscle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 36500,
        ['CanBoost'] = true,
    },
    [GetHashKey('voodoo')] = {
        ['Vehicle'] = 'voodoo',
        ['Model'] = 'Declasse',
        ['Name'] = 'Voodoo',
        ['ShopClass'] = 'Muscle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 35500,
        ['CanBoost'] = true,
    },
    [GetHashKey('faction')] = {
        ['Vehicle'] = 'faction',
        ['Model'] = 'Willard',
        ['Name'] = 'Faction',
        ['ShopClass'] = 'Muscle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 36500,
        ['CanBoost'] = true,
    },
    [GetHashKey('faction3')] = {
        ['Vehicle'] = 'faction3',
        ['Model'] = 'Willard',
        ['Name'] = 'Faction Custom',
        ['ShopClass'] = 'Muscle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 50500,
        ['CanBoost'] = true,
    },
    [GetHashKey('moonbeam')] = {
        ['Vehicle'] = 'moonbeam',
        ['Model'] = 'Declasse',
        ['Name'] = 'Moonbeam',
        ['ShopClass'] = 'Muscle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 51500,
        ['CanBoost'] = true,
    },
    [GetHashKey('ratloader')] = {
        ['Vehicle'] = 'ratloader',
        ['Model'] = 'Bravado',
        ['Name'] = 'Rat Truck',
        ['ShopClass'] = 'Muscle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 47500,
        ['CanBoost'] = false,
    },
    [GetHashKey('slamvan')] = {
        ['Vehicle'] = 'slamvan',
        ['Model'] = 'Vapid',
        ['Name'] = 'Slamvan',
        ['ShopClass'] = 'Muscle',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 47500,
        ['CanBoost'] = false,
    },
    -- Off-Road
    [GetHashKey('bfinjection')] = {
        ['Vehicle'] = 'bfinjection',
        ['Model'] = 'BF',
        ['Name'] = 'Injection',
        ['ShopClass'] = 'Off-Road',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 50000,
        ['CanBoost'] = false,
    },
    [GetHashKey('bifta')] = {
        ['Vehicle'] = 'bifta',
        ['Model'] = 'BF',
        ['Name'] = 'Bifta',
        ['ShopClass'] = 'Off-Road',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 35000,
        ['CanBoost'] = false,
    },
    [GetHashKey('dune')] = {
        ['Vehicle'] = 'dune',
        ['Model'] = 'BF',
        ['Name'] = 'Dune Buggy',
        ['ShopClass'] = 'Off-Road',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 34500,
        ['CanBoost'] = false,
    },
    [GetHashKey('hellion')] = {
        ['Vehicle'] = 'hellion',
        ['Model'] = 'Annis',
        ['Name'] = 'Hellion',
        ['ShopClass'] = 'Off-Road',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 68000,
        ['CanBoost'] = true,
    },
    [GetHashKey('blazer')] = {
        ['Vehicle'] = 'blazer',
        ['Model'] = 'Nagasaki',
        ['Name'] = 'Blazer',
        ['ShopClass'] = 'Off-Road',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 15000,
        ['CanBoost'] = false,
    },
    [GetHashKey('bodhi2')] = {
        ['Vehicle'] = 'bodhi2',
        ['Model'] = 'Canis',
        ['Name'] = 'Bodhi',
        ['ShopClass'] = 'Off-Road',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 45000,
        ['CanBoost'] = false,
    },
    [GetHashKey('kalahari')] = {
        ['Vehicle'] = 'kalahari',
        ['Model'] = 'Canis',
        ['Name'] = 'Kalahari',
        ['ShopClass'] = 'Off-Road',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 43500,
        ['CanBoost'] = false,
    },
    [GetHashKey('outlaw')] = {
        ['Vehicle'] = 'outlaw',
        ['Model'] = 'Nagasaki',
        ['Name'] = 'Outlaw',
        ['ShopClass'] = 'Off-Road',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 44500,
        ['CanBoost'] = false,
    },
    -- SUVS
    [GetHashKey('baller')] = {
        ['Vehicle'] = 'baller',
        ['Model'] = 'Gallivanter',
        ['Name'] = 'Baller',
        ['ShopClass'] = 'Suv',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 75000,
        ['CanBoost'] = true,
    },
    [GetHashKey('baller3')] = {
        ['Vehicle'] = 'baller3',
        ['Model'] = 'Gallivanter',
        ['Name'] = 'Baller LE',
        ['ShopClass'] = 'Suv',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 85000,
        ['CanBoost'] = true,
    },
    [GetHashKey('bjxl')] = {
        ['Vehicle'] = 'bjxl',
        ['Model'] = 'Karin',
        ['Name'] = 'BeeJay XL',
        ['ShopClass'] = 'Suv',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 65000,
        ['CanBoost'] = true,
    },
    [GetHashKey('dubsta2')] = {
        ['Vehicle'] = 'dubsta2',
        ['Model'] = 'Benefactor',
        ['Name'] = 'Dubsta',
        ['ShopClass'] = 'Suv',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 87500,
        ['CanBoost'] = true,
    },
    [GetHashKey('granger')] = {
        ['Vehicle'] = 'granger',
        ['Model'] = 'Declasse',
        ['Name'] = 'Granger',
        ['ShopClass'] = 'Suv',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 83500,
        ['CanBoost'] = true,
    },
    [GetHashKey('gresley')] = {
        ['Vehicle'] = 'gresley',
        ['Model'] = 'Bravado',
        ['Name'] = 'Gresley',
        ['ShopClass'] = 'Suv',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 75500,
        ['CanBoost'] = true,
    },
    [GetHashKey('huntley')] = {
        ['Vehicle'] = 'huntley',
        ['Model'] = 'Enus',
        ['Name'] = 'Huntley',
        ['ShopClass'] = 'Suv',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 73500,
        ['CanBoost'] = true,
    },
    [GetHashKey('novak')] = {
        ['Vehicle'] = 'novak',
        ['Model'] = 'Lampadati',
        ['Name'] = 'Novak',
        ['ShopClass'] = 'Suv',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 85500,
        ['CanBoost'] = true,
    },
    [GetHashKey('rebla')] = {
        ['Vehicle'] = 'rebla',
        ['Model'] = 'Übermacht',
        ['Name'] = 'Rebla',
        ['ShopClass'] = 'Suv',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 90000,
        ['CanBoost'] = true,
    },
    [GetHashKey('toros')] = {
        ['Vehicle'] = 'toros',
        ['Model'] = 'Pegassi',
        ['Name'] = 'Toros',
        ['ShopClass'] = 'Suv',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 115000,
        ['CanBoost'] = true,
    },
    -- Sedans
    [GetHashKey('asea')] = {
        ['Vehicle'] = 'asea',
        ['Model'] = 'Declasse',
        ['Name'] = 'Asea',
        ['ShopClass'] = 'Sedans',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 35000,
        ['CanBoost'] = true,
    },
    [GetHashKey('emperor')] = {
        ['Vehicle'] = 'emperor',
        ['Model'] = 'Albany',
        ['Name'] = 'Emperor',
        ['ShopClass'] = 'Sedans',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 34500,
        ['CanBoost'] = false,
    },
    [GetHashKey('stratum')] = {
        ['Vehicle'] = 'stratum',
        ['Model'] = 'Zirconium',
        ['Name'] = 'Stratum',
        ['ShopClass'] = 'Sedans',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 46550,
        ['CanBoost'] = true,
    },
    [GetHashKey('asterope')] = {
        ['Vehicle'] = 'asterope',
        ['Model'] = 'Karin',
        ['Name'] = 'Asterope',
        ['ShopClass'] = 'Sedans',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 37500,
        ['CanBoost'] = true,
    },
    [GetHashKey('premier')] = {
        ['Vehicle'] = 'premier',
        ['Model'] = 'Declasse',
        ['Name'] = 'Premier',
        ['ShopClass'] = 'Sedans',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 40500,
        ['CanBoost'] = true,
    },
    [GetHashKey('washington')] = {
        ['Vehicle'] = 'washington',
        ['Model'] = 'Albany',
        ['Name'] = 'Washington',
        ['ShopClass'] = 'Sedans',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 38500,
        ['CanBoost'] = true,
    },
    [GetHashKey('warrener')] = {
        ['Vehicle'] = 'warrener',
        ['Model'] = 'Vulcar',
        ['Name'] = 'Warrener',
        ['ShopClass'] = 'Sedans',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 45500,
        ['CanBoost'] = true,
    },
    [GetHashKey('primo')] = {
        ['Vehicle'] = 'primo',
        ['Model'] = 'Albany',
        ['Name'] = 'Primo',
        ['ShopClass'] = 'Sedans',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 42500,
        ['CanBoost'] = true,
    },
    [GetHashKey('cognoscenti')] = {
        ['Vehicle'] = 'cognoscenti',
        ['Model'] = 'Enus',
        ['Name'] = 'Cognoscenti',
        ['ShopClass'] = 'Sedans',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 85000,
        ['CanBoost'] = true,
    },
    [GetHashKey('superd')] = {
        ['Vehicle'] = 'superd',
        ['Model'] = 'Enus',
        ['Name'] = 'Super Diamond',
        ['ShopClass'] = 'Sedans',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 115000,
        ['CanBoost'] = true,
    },
    -- Sports
    [GetHashKey('banshee')] = {
        ['Vehicle'] = 'banshee',
        ['Model'] = 'Bravado',
        ['Name'] = 'Banshee',
        ['ShopClass'] = 'Sports',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 90000,
        ['CanBoost'] = true,
    },
    [GetHashKey('buffalo')] = {
        ['Vehicle'] = 'buffalo',
        ['Model'] = 'Bravado',
        ['Name'] = 'Buffalo',
        ['ShopClass'] = 'Sports',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 85000,
        ['CanBoost'] = true,
    },
    [GetHashKey('comet2')] = {
        ['Vehicle'] = 'comet2',
        ['Model'] = 'Pfister',
        ['Name'] = 'Comet',
        ['ShopClass'] = 'Sports',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 87500,
        ['CanBoost'] = true,
    },
    [GetHashKey('coquette')] = {
        ['Vehicle'] = 'coquette',
        ['Model'] = 'Invetero',
        ['Name'] = 'Coquette',
        ['ShopClass'] = 'Sports',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 92500,
        ['CanBoost'] = true,
        ['CanBoost'] = true,
    },
    [GetHashKey('kuruma')] = {
        ['Vehicle'] = 'kuruma',
        ['Model'] = 'Karin',
        ['Name'] = 'Kuruma',
        ['ShopClass'] = 'Sports',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 95000,
        ['CanBoost'] = true,
    },
    [GetHashKey('jugular')] = {
        ['Vehicle'] = 'jugular',
        ['Model'] = 'Ocelot',
        ['Name'] = 'Jugular',
        ['ShopClass'] = 'Sports',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 90000,
        ['CanBoost'] = true,
    },
    [GetHashKey('komoda')] = {
        ['Vehicle'] = 'komoda',
        ['Model'] = 'Lampadati',
        ['Name'] = 'Komoda',
        ['ShopClass'] = 'Sports',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 100000,
        ['CanBoost'] = true,
    },
    [GetHashKey('schafter3')] = {
        ['Vehicle'] = 'schafter3',
        ['Model'] = 'Benefactor',
        ['Name'] = 'Schafter V12',
        ['ShopClass'] = 'Sports',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 95500,
        ['CanBoost'] = true,
    },
    [GetHashKey('sultan')] = {
        ['Vehicle'] = 'sultan',
        ['Model'] = 'Karin',
        ['Name'] = 'Sultan',
        ['ShopClass'] = 'Sports',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 92500,
        ['CanBoost'] = true,
    },
    [GetHashKey('sultan2')] = {
        ['Vehicle'] = 'sultan2',
        ['Model'] = 'Karin',
        ['Name'] = 'Sultan Sports',
        ['ShopClass'] = 'Sports',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 95500,
        ['CanBoost'] = true,
    },
    [GetHashKey('calico')] = {
        ['Vehicle'] = 'calico',
        ['Model'] = 'Karin',
        ['Name'] = 'Calico',
        ['ShopClass'] = 'Sports',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 96000,
        ['CanBoost'] = true,
    },
    [GetHashKey('specter')] = {
        ['Vehicle'] = 'specter',
        ['Model'] = 'Dewbauchee',
        ['Name'] = 'Specter',
        ['ShopClass'] = 'Sports',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 93550,
        ['CanBoost'] = true,
    },
    [GetHashKey('neon')] = {
        ['Vehicle'] = 'neon',
        ['Model'] = 'Pfister',
        ['Name'] = 'Neon',
        ['ShopClass'] = 'Sports',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 100000,
        ['CanBoost'] = true,
    },
    -- Coupes
    [GetHashKey('zion')] = {
        ['Vehicle'] = 'zion',
        ['Model'] = 'Übermacht',
        ['Name'] = 'Zion',
        ['ShopClass'] = 'Coupes',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 64500,
        ['CanBoost'] = true,
    },
    [GetHashKey('felon')] = {
        ['Vehicle'] = 'felon',
        ['Model'] = 'Lampadati',
        ['Name'] = 'Felon',
        ['ShopClass'] = 'Coupes',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 65400,
        ['CanBoost'] = true,
    },
    [GetHashKey('jackal')] = {
        ['Vehicle'] = 'jackal',
        ['Model'] = 'Ocelot',
        ['Name'] = 'Jackal',
        ['ShopClass'] = 'Coupes',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 68500,
        ['CanBoost'] = true,
    },
    [GetHashKey('exemplar')] = {
        ['Vehicle'] = 'exemplar',
        ['Model'] = 'Dewbauchee',
        ['Name'] = 'Exemplar',
        ['ShopClass'] = 'Coupes',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 75500,
        ['CanBoost'] = true,
    },
    [GetHashKey('f620')] = {
        ['Vehicle'] = 'f620',
        ['Model'] = 'Ocelot',
        ['Name'] = 'F620',
        ['ShopClass'] = 'Coupes',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 75500,
        ['CanBoost'] = true,
    },
    [GetHashKey('windsor')] = {
        ['Vehicle'] = 'windsor',
        ['Model'] = 'Enus',
        ['Name'] = 'Windsor',
        ['ShopClass'] = 'Coupes',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 85000,
        ['CanBoost'] = true,
    },
    [GetHashKey('cogcabrio')] = {
        ['Vehicle'] = 'cogcabrio',
        ['Model'] = 'Enus',
        ['Name'] = 'Cogcabrio',
        ['ShopClass'] = 'Coupes',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 83500,
        ['CanBoost'] = true,
    },
    [GetHashKey('oracle')] = {
        ['Vehicle'] = 'oracle',
        ['Model'] = 'Übermacht',
        ['Name'] = 'Oracle',
        ['ShopClass'] = 'Coupes',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 84500,
        ['CanBoost'] = true,
    },
    [GetHashKey('previon')] = {
        ['Vehicle'] = 'previon',
        ['Model'] = 'Karin',
        ['Name'] = 'Previon',
        ['ShopClass'] = 'Coupes',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 81500,
        ['CanBoost'] = true,
    },
    -- Vans
    [GetHashKey('surfer')] = {
        ['Vehicle'] = 'surfer',
        ['Model'] = 'BF',
        ['Name'] = 'Surfer',
        ['ShopClass'] = 'Vans',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Van',
        ['Price'] = 55500,
        ['CanBoost'] = false,
    },
    [GetHashKey('speedo')] = {
        ['Vehicle'] = 'speedo',
        ['Model'] = 'Vapid',
        ['Name'] = 'Speedo',
        ['ShopClass'] = 'Vans',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Van',
        ['Price'] = 51500,
        ['CanBoost'] = false,
    },
    [GetHashKey('bobcatxl')] = {
        ['Vehicle'] = 'bobcatxl',
        ['Model'] = 'Vapid',
        ['Name'] = 'BobcatXL',
        ['ShopClass'] = 'Vans',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Van',
        ['Price'] = 55000,
        ['CanBoost'] = false,
    },
    [GetHashKey('bison')] = {
        ['Vehicle'] = 'bison',
        ['Model'] = 'Bravado',
        ['Name'] = 'Bison',
        ['ShopClass'] = 'Vans',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Van',
        ['Price'] = 50500,
        ['CanBoost'] = false,
    },
    [GetHashKey('youga')] = {
        ['Vehicle'] = 'youga',
        ['Model'] = 'Bravado',
        ['Name'] = 'Youga',
        ['ShopClass'] = 'Vans',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Van',
        ['Price'] = 48500,
        ['CanBoost'] = false,
    },
    [GetHashKey('gburrito')] = {
        ['Vehicle'] = 'gburrito',
        ['Model'] = 'Declasse',
        ['Name'] = 'Burrito Mod',
        ['ShopClass'] = 'Vans',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Van',
        ['Price'] = 47550,
        ['CanBoost'] = false,
    },
    [GetHashKey('minivan')] = {
        ['Vehicle'] = 'minivan',
        ['Model'] = 'Vapid',
        ['Name'] = 'Minivan',
        ['ShopClass'] = 'Vans',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Van',
        ['Price'] = 45550,
        ['CanBoost'] = false,
    },
    [GetHashKey('rumpo')] = {
        ['Vehicle'] = 'rumpo',
        ['Model'] = 'Bravado',
        ['Name'] = 'Rumpo',
        ['ShopClass'] = 'Vans',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Van',
        ['Price'] = 46440,
        ['CanBoost'] = false,
    },
    [GetHashKey('rumpo3')] = {
        ['Vehicle'] = 'rumpo3',
        ['Model'] = 'Bravado',
        ['Name'] = 'Rumpo Off-Road',
        ['ShopClass'] = 'Vans',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Van',
        ['Price'] = 48740,
        ['CanBoost'] = false,
    },
    -- Custom
    [GetHashKey('gtr')] = {
        ['Vehicle'] = 'gtr',
        ['Model'] = 'Nissan',
        ['Name'] = 'GTR',
        ['ShopClass'] = 'Custom',
        ['Class'] = 'S',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 245000,
    },
    [GetHashKey('fnf4r34')] = {
        ['Vehicle'] = 'fnf4r34',
        ['Model'] = 'Nissan',
        ['Name'] = 'Skyline',
        ['ShopClass'] = 'Custom',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 225000,
    },
    [GetHashKey('s15rb')] = {
        ['Vehicle'] = 's15rb',
        ['Model'] = 'Nissan',
        ['Name'] = 'S15',
        ['ShopClass'] = 'Custom',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 195000,
    },
    [GetHashKey('audirs6tk')] = {
        ['Vehicle'] = 'audirs6tk',
        ['Model'] = 'Audi',
        ['Name'] = 'RS6',
        ['ShopClass'] = 'Custom',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 275000,
    },
    [GetHashKey('rr14')] = {
        ['Vehicle'] = 'rr14',
        ['Model'] = 'Range Rover',
        ['Name'] = 'Evoque',
        ['ShopClass'] = 'Custom',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 230000,
    },
    -- [GetHashKey('landcruiser')] = {
    --     ['Vehicle'] = 'landcruiser',
    --     ['Model'] = 'Toyota',
    --     ['Name'] = 'Landcruiser',
    --     ['ShopClass'] = 'Custom',
    --     ['Class'] = 'B',
    --     ['Picture'] = 'None',
    --     ['Type'] = 'Car',
    --     ['Price'] = 230000,
    -- },
    [GetHashKey('evo9')] = {
        ['Vehicle'] = 'evo9',
        ['Model'] = 'Mitsubishi',
        ['Name'] = 'Lancer Evo',
        ['ShopClass'] = 'Custom',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 275000,
    },
    [GetHashKey('subwrx')] = {
        ['Vehicle'] = 'subwrx',
        ['Model'] = 'Subaru',
        ['Name'] = 'Impreza WRX',
        ['ShopClass'] = 'Custom',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 275000,
    },
    [GetHashKey('a80')] = {
        ['Vehicle'] = 'a80',
        ['Model'] = 'Toyota',
        ['Name'] = 'A80 Supra',
        ['ShopClass'] = 'Custom',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 195000,
    },
    [GetHashKey('GT63')] = {
        ['Vehicle'] = 'GT63',
        ['Model'] = 'Mercedes',
        ['Name'] = 'GT63',
        ['ShopClass'] = 'Custom',
        ['Class'] = 'S',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 285000,
    },
    [GetHashKey('GTRC')] = {
        ['Vehicle'] = 'GTRC',
        ['Model'] = 'Mercedes',
        ['Name'] = 'GTR-C',
        ['ShopClass'] = 'Custom',
        ['Class'] = 'S',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 295000,
    },
    [GetHashKey('22g63')] = {
        ['Vehicle'] = '22g63',
        ['Model'] = 'Mercedes',
        ['Name'] = 'G63',
        ['ShopClass'] = 'Custom',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 230000,
    },
    [GetHashKey('srt8b')] = {
        ['Vehicle'] = 'srt8b',
        ['Model'] = 'Jeep',
        ['Name'] = 'Track Hawk',
        ['ShopClass'] = 'Custom',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 230000,
    },
    -- POLICE
    [GetHashKey('polvic')] = {
        ['Vehicle'] = 'polvic',
        ['Model'] = 'Ford',
        ['Name'] = 'Crownvic',
        ['ShopClass'] = 'Police',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 100000,
    },
    [GetHashKey('polchal')] = {
        ['Vehicle'] = 'polchal',
        ['Model'] = 'Dodge',
        ['Name'] = 'Challenger',
        ['ShopClass'] = 'Police',
        ['Class'] = 'S',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 200000,
    },
    [GetHashKey('polstang')] = {
        ['Vehicle'] = 'polstang',
        ['Model'] = 'Ford',
        ['Name'] = 'Mustang',
        ['ShopClass'] = 'Police',
        ['Class'] = 'S',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 200000,
    },
    [GetHashKey('polvette')] = {
        ['Vehicle'] = 'polvette',
        ['Model'] = 'Chevrolet',
        ['Name'] = 'Corvette',
        ['ShopClass'] = 'Police',
        ['Class'] = 'S',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 200000,
    },
    [GetHashKey('polexp')] = {
        ['Vehicle'] = 'polexp',
        ['Model'] = 'Ford',
        ['Name'] = 'Explorer',
        ['ShopClass'] = 'Police',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 150000,
    },
    [GetHashKey('polchar')] = {
        ['Vehicle'] = 'polchar',
        ['Model'] = 'Dodge',
        ['Name'] = 'Charger',
        ['ShopClass'] = 'Police',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 200000,
    },
    [GetHashKey('polbike')] = {
        ['Vehicle'] = 'polbike',
        ['Model'] = 'Nagasaki',
        ['Name'] = 'PD Crosser',
        ['ShopClass'] = 'Police',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Motorcycle',
        ['Siren'] = 'RESIDENT_VEHICLES_SIREN_WAIL_03',
        ['Price'] = 110000,
    },
    -- POLICE HELI
    [GetHashKey('airone')] = {
        ['Vehicle'] = 'airone',
        ['Model'] = '',
        ['Name'] = 'airone',
        ['ShopClass'] = 'Police',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Helicopter',
        ['Siren'] = '',
    },
    -- POLICE UC
    [GetHashKey('ucbanshee')] = {
        ['Vehicle'] = 'ucbanshee',
        ['Model'] = 'Bravado',
        ['Name'] = 'Banshee UC',
        ['ShopClass'] = 'Police',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 100000,
    },
    [GetHashKey('ucrancher')] = {
        ['Vehicle'] = 'ucrancher',
        ['Model'] = 'Declasse',
        ['Name'] = 'Rancher UC',
        ['ShopClass'] = 'Police',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 100000,
    },
    [GetHashKey('ucbuffalo')] = {
        ['Vehicle'] = 'ucbuffalo',
        ['Model'] = 'Bravado',
        ['Name'] = 'Buffalo UC',
        ['ShopClass'] = 'Police',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 100000,
    },
    [GetHashKey('ucballer')] = {
        ['Vehicle'] = 'ucballer',
        ['Model'] = 'Gallivanter',
        ['Name'] = 'Baller UC',
        ['ShopClass'] = 'Police',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'VEHICLES_HORNS_SIREN_1',
        ['Price'] = 100000,
    },
    -- EMS
    [GetHashKey('emsspeedo')] = {
        ['Vehicle'] = 'emsspeedo',
        ['Model'] = 'Vapid',
        ['Name'] = 'Speedo',
        ['ShopClass'] = 'EMS',
        ['Class'] = 'A',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Siren'] = 'RESIDENT_VEHICLES_SIREN_WAIL_01'
    },
    [GetHashKey('airtwo')] = {
        ['Vehicle'] = 'airtwo',
        ['Model'] = '',
        ['Name'] = 'Air Two',
        ['ShopClass'] = 'EMS',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Helicopter',
        ['Siren'] = ''
    },
    -- JOB VEHS
    [GetHashKey('taxi')] = {
        ['Vehicle'] = 'taxi',
        ['Model'] = 'Vapid',
        ['Name'] = 'Taxi',
        ['ShopClass'] = 'Job',
        ['Class'] = 'B',
        ['Picture'] = 'None',
        ['Type'] = 'Car',
        ['Price'] = 29500,
    }
}

Shared.VehicleColors = {
    [1] = "Metallic Graphite Black",[2] = "Metallic Black Steel",[3] = "Metallic Dark Silver",[4] = "Metallic Silver",[5] = "Metallic Blue Silver",[6] = "Metallic Steel Gray",[7] = "Metallic Shadow Silver",[8] = "Metallic Stone Silver",[9] = "Metallic Midnight Silver",[10] = "Metallic Gun Metal",
    [11] = "Metallic Anthracite Grey",[12] = "Matte Black",[13] = "Matte Gray",[14] = "Matte Light Grey",[15] = "Util Black",[16] = "Util Black Poly",[17] = "Util Dark silver",[18] = "Util Silver",[19] = "Util Gun Metal",[20] = "Util Shadow Silver",
    [21] = "Worn Black",[22] = "Worn Graphite",[23] = "Worn Silver Grey",[24] = "Worn Silver",[25] = "Worn Blue Silver",[26] = "Worn Shadow Silver",[27] = "Metallic Red",[28] = "Metallic Torino Red",[29] = "Metallic Formula Red",[30] = "Metallic Blaze Red",
    [31] = "Metallic Graceful Red",[32] = "Metallic Garnet Red",[33] = "Metallic Desert Red",[34] = "Metallic Cabernet Red",[35] = "Metallic Candy Red",[36] = "Metallic Sunrise Orange",[37] = "Metallic Classic Gold",[38] = "Metallic Orange",[39] = "Matte Red",[40] = "Matte Dark Red",
    [41] = "Matte Orange",[42] = "Matte Yellow",[43] = "Util Red",[44] = "Util Bright Red",[45] = "Util Garnet Red",[46] = "Worn Red",[47] = "Worn Golden Red",[48] = "Worn Dark Red",[49] = "Metallic Dark Green",[50] = "Metallic Racing Green",
    [51] = "Metallic Sea Green",[52] = "Metallic Olive Green",[53] = "Metallic Green",[54] = "Metallic Gasoline Blue Green",[55] = "Matte Lime Green",[56] = "Util Dark Green",[57] = "Util Green",[58] = "Worn Dark Green",[59] = "Worn Green",[60] = "Worn Sea Wash",
    [61] = "Metallic Midnight Blue",[62] = "Metallic Dark Blue",[63] = "Metallic Saxony Blue",[64] = "Metallic Blue",[65] = "Metallic Mariner Blue",[66] = "Metallic Harbor Blue",[67] = "Metallic Diamond Blue",[68] = "Metallic Surf Blue",[69] = "Metallic Nautical Blue",[70] = "Metallic Bright Blue",
    [71] = "Metallic Purple Blue",[72] = "Metallic Spinnaker Blue",[73] = "Metallic Ultra Blue",[74] = "Metallic Bright Blue",[75] = "Util Dark Blue",[76] = "Util Midnight Blue",[77] = "Util Blue",[78] = "Util Sea Foam Blue",[79] = "Uil Lightning blue",[80] = "Util Maui Blue Poly",
    [81] = "Util Bright Blue",[82] = "Matte Dark Blue",[83] = "Matte Blue",[84] = "Matte Midnight Blue",[85] = "Worn Dark blue",[86] = "Worn Blue",[87] = "Worn Light blue",[88] = "Metallic Taxi Yellow",[89] = "Metallic Race Yellow",[90] = "Metallic Bronze",
    [91] = "Metallic Yellow Bird",[92] = "Metallic Lime",[93] = "Metallic Champagne",[94] = "Metallic Pueblo Beige",[95] = "Metallic Dark Ivory",[96] = "Metallic Choco Brown",[97] = "Metallic Golden Brown",[98] = "Metallic Light Brown",[99] = "Metallic Straw Beige",[100] = "Metallic Moss Brown",
    [101] = "Metallic Biston Brown",[102] = "Metallic Beechwood",[103] = "Metallic Dark Beechwood",[104] = "Metallic Choco Orange",[105] = "Metallic Beach Sand",[106] = "Metallic Sun Bleeched Sand",[107] = "Metallic Cream",[108] = "Util Brown",[109] = "Util Medium Brown",[110] = "Util Light Brown",
    [111] = "Metallic White",[112] = "Metallic Frost White",[113] = "Worn Honey Beige",[114] = "Worn Brown",[115] = "Worn Dark Brown",[116] = "Worn straw beige",[117] = "Brushed Steel",[118] = "Brushed Black steel",[119] = "Brushed Aluminium",[120] = "Chrome",
    [121] = "Worn Off White",[122] = "Util Off White",[123] = "Worn Orange",[124] = "Worn Light Orange",[125] = "Metallic Securicor Green",[126] = "Worn Taxi Yellow",[127] = "police car blue",[128] = "Matte Green",[129] = "Matte Brown",[130] = "Worn Orange",
    [131] = "Matte White",[132] = "Worn White",[133] = "Worn Olive Army Green",[134] = "Pure White",[135] = "Hot Pink",[136] = "Salmon pink",[137] = "Metallic Vermillion Pink",[138] = "Orange",[139] = "Green",[140] = "Blue",
    [141] = "Mettalic Black Blue",[142] = "Metallic Black Purple",[143] = "Metallic Black Red",[144] = "hunter green",[145] = "Metallic Purple",[146] = "Metaillic V Dark Blue",[147] = "MODSHOP BLACK1",[148] = "Matte Purple",[149] = "Matte Dark Purple",[150] = "Metallic Lava Red",
    [151] = "Matte Forest Green",[152] = "Matte Olive Drab",[153] = "Matte Desert Brown",[154] = "Matte Desert Tan",[155] = "Matte Foilage Green",[156] = "DEFAULT ALLOY COLOR",[157] = "Epsilon Blue",[158] = "Unknown",
}